---
AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon aurora-postgresql 
Parameters:
  DBClusterIdentifier:
    Description: Enter the DB  Name
    Type: String
  BackupRetentionPeriod:
    Description: You must specify a minimum value of 1
    Type: Number
    Default: '1'
    AllowedValues:
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - '10'
    - '11'
    - '12'
    - '13'
    - '14'
    - '15'
    - '16'
    - '17'
    - '18'
    - '19'
    - '20'
    - '21'
    - '22'
    - '23'
    - '24'
    - '25'
    - '26'
    - '27'
    - '28'
    - '29'
    - '30'
    - '31'
    - '32'
    - '33'
    - '34'
    - '35'
  DatabaseName:
    Description: Enter the DB  Name
    Type: String
  MasterUsername:
    Description: Enter  the MasterUsername
    Type: String
  MasterUserPassword:
    NoEcho: 'true'
    Description: Enter  the MasterUserPassword
    Type: String
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: must contain only alphanumeric characters
  DBClusterParameterGroupName:
    Type: String
    Description: Enter the name of DBClusterParameterGroup
  DBSubnetGroupName:
    Type: String
    Description: Name of subnet group
  DeletionProtection:
    Type: String
    Description: Delete Protection for  Cluster
    Default: false
    AllowedValues:
    - 'true'
    - 'false'
  Family:
    Type: String
    Description: Parameter group family
    Default: aurora-postgresql11
    AllowedValues:
    - aurora-postgresql9.6
    - aurora-postgresql10
    - aurora-postgresql11
  EngineVersion:
    Type: String
    Description: The version number of the database engine to use
    Default: '11.7'
    AllowedValues:
    - " 9.6.19"
    - " 10.7"
    - '10.11'
    - '10.12'
    - '10.13'
    - '10.14'
    - '11.6'
    - '11.7'
    - '11.8'
    - '11.9'
  KmsKeyId:
    Description: The KMS key ID
    Type: String
  Port:
    Description: Port number
    Type: Number
    Default: '5432'
  PreferredBackupWindow:
    Description: Enter Preferred Backup Window Time (UTC).
    Type: String
    Default: 17:00-19:00
  PreferredMaintenanceWindow:
    Description: Enter Preferred Maintenance Window Time (UTC)
    Type: String
    Default: Sun:19:00-Sun:23:00
  StorageEncrypted:
    Type: String
    Description: StorageEncrypted
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  AllowMajorVersionUpgrade:
    AllowedValues:
    - 'true'
    - 'false'
    Type: String
    Description: AllowMajorVersionUpgrade
  DBInstanceClass:
    Type: String
    Description: Select The instance DBInstanceClass
    AllowedValues:
    - db.t4g.small 
  DBInstanceName:
    Default: MyInstance
    Description: Instance name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric
      characters.
  DeleteAutomatedBackups:
    Description: DeleteAutomatedBackups
    AllowedValues:
    - 'true'
    - 'false'
    Type: String
  EnablePerformanceInsights:
    Description: EnablePerformanceInsights
    AllowedValues:
    - 'true'
    - 'false'
    Type: String
    Default: 'true'
  MonitoringInterval:
    Description: MonitoringInterval
    Type: Number
    Default: '0'
    AllowedValues:
    - '0'
    - '1'
    - '5'
    - '10'
    - '15'
    - '30'
    - '60'
  MonitoringRoleArn:
    Description: MonitoringRoleArn
    Type: String
  PerformanceInsightsKMSKeyId:
    Description: PerformanceInsightsKMSKeyId
    Type: String
  PerformanceInsightsRetentionPeriod:
    Description: PerformanceInsightsRetentionPeriod
    Type: Number
    AllowedValues:
    - '7'
    - '731'
  PubliclyAccessible:
    Description: PubliclyAccessible
    AllowedValues:
    - 'true'
    - 'false'
    Type: String
    Default: 'false'
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The subnets where DB Cluster will be created.
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: List of VPC IDs.
  Name:
    Type: String
    Default: AXAWS
    Description: Name starting with AXAWS
  
    Type: String
    Description: Application Relation/Resource Manager
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: VPC
      Parameters:
      - VPCId
      - Subnets
    - Label:
        default: DB  Configuration
      Parameters:
      - DBClusterIdentifier
      - BackupRetentionPeriod
      - DatabaseName
      - MasterUsername
      - MasterUserPassword
      - DBClusterParameterGroupName
      - DeletionProtection
      - Family
      - EngineVersion
      - KmsKeyId
      - Port
      - PreferredBackupWindow
      - PreferredMaintenanceWindow
      - StorageEncrypted
      - AllowMajorVersionUpgrade
      - DBInstanceClass
      - DBInstanceName
      - DeleteAutomatedBackups
      - EnablePerformanceInsights
      - MonitoringInterval
      - MonitoringRoleArn
      - PerformanceInsightsKMSKeyId
      - PerformanceInsightsRetentionPeriod
      - PubliclyAccessible
      - DBSubnetGroupName
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Sub: "${DBClusterIdentifier}-SecurityGroup"
      GroupDescription: Allow https traffic to cluster
      VpcId:
        Ref: VPCId
  DBCluster:
    Type: AWS::RDS::DBCluster
    DependsOn:
    - DBClusterParameterGroup
    - DBSubnetGroup
    Properties:
      DBClusterIdentifier:
        Ref: DBClusterIdentifier
      BackupRetentionPeriod:
        Ref: BackupRetentionPeriod
      DatabaseName:
        Ref: DatabaseName
      DBClusterParameterGroupName:
        Ref: DBClusterParameterGroup
      DBSubnetGroupName:
        Ref: DBSubnetGroupName
      DeletionProtection:
        Ref: DeletionProtection
      EnableCloudwatchLogsExports:
      - postgresql
      Engine: aurora-postgresql
      EngineVersion:
        Ref: EngineVersion
      KmsKeyId:
        Ref: KmsKeyId
      MasterUsername:
        Ref: MasterUsername
      MasterUserPassword:
        Ref: MasterUserPassword
      Port:
        Ref: Port
      PreferredBackupWindow:
        Ref: PreferredBackupWindow
      PreferredMaintenanceWindow:
        Ref: PreferredMaintenanceWindow
      StorageEncrypted:
        Ref: StorageEncrypted
      VpcSecurityGroupIds:
      - Ref: InstanceSecurityGroup
  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: DBClusterParameterGroup
      Family:
        Ref: Family
      Parameters:
        rds.force_ssl: '1'
  DBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: DBCluster
    Properties:
      AllowMajorVersionUpgrade:
        Ref: AllowMajorVersionUpgrade
      DBClusterIdentifier:
        Ref: DBClusterIdentifier
      DBInstanceClass:
        Ref: DBInstanceClass
      DBInstanceIdentifier:
        Ref: DBInstanceName
      DBParameterGroupName:
        Ref: DBParameterGroup
      DeleteAutomatedBackups:
        Ref: DeleteAutomatedBackups
      EnablePerformanceInsights:
        Ref: EnablePerformanceInsights
      MonitoringInterval:
        Ref: MonitoringInterval
      MonitoringRoleArn:
        Ref: MonitoringRoleArn
      PerformanceInsightsKMSKeyId:
        Ref: PerformanceInsightsKMSKeyId
      PerformanceInsightsRetentionPeriod:
        Ref: PerformanceInsightsRetentionPeriod
      PubliclyAccessible:
        Ref: PubliclyAccessible
      Engine: aurora-postgresql
  
    Type: AWS::RDS::DBInstance
    DependsOn: DBCluster
    Properties:
      AllowMajorVersionUpgrade:
        Ref: AllowMajorVersionUpgrade
      DBClusterIdentifier:
        Ref: DBClusterIdentifier
      DBInstanceClass:
        Ref: DBInstanceClass
      DBInstanceIdentifier:
        Fn::Sub: "${DBInstanceName}-r1"
      DBParameterGroupName:
        Ref: DBParameterGroup
      DeleteAutomatedBackups:
        Ref: DeleteAutomatedBackups
      EnablePerformanceInsights:
        Ref: EnablePerformanceInsights
      MonitoringInterval:
        Ref: MonitoringInterval
      MonitoringRoleArn:
        Ref: MonitoringRoleArn
      PerformanceInsightsKMSKeyId:
        Ref: PerformanceInsightsKMSKeyId
      PerformanceInsightsRetentionPeriod:
        Ref: PerformanceInsightsRetentionPeriod
      PubliclyAccessible:
        Ref: PubliclyAccessible
      Engine: aurora-postgresql
  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: DBParameterGroup
      Family:
        Ref: Family
      Parameters:
        log_statement: ddl
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      DBSubnetGroupName:
        Ref: DBSubnetGroupName
      SubnetIds:
        Ref: Subnets
