apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hss-hackathon-eks-1
  region: us-east-1
  version: "1.21"

iam:
  withOIDC: true

vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-071aa8a15f61ca992 }
      us-east-1b: { id: subnet-0679bfc7ba8f09f83 }
  clusterEndpoints:
    publicAccess: true

managedNodeGroups:
  - name: hss-hackathon-eks-nodegroup-1
    subnets: ["subnet-071aa8a15f61ca992", "subnet-0679bfc7ba8f09f83"]
    instanceType: t3.medium
    disableIMDSv1: true
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: "eks-ssh"